apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: {{ .Values.APP_DEVELOPMENT_NAME }}
  labels:
    {{- include "helm-labels" . }}
    {{- include "default-k8-labels" . }}
data:
  ENVIRONMENT: {{ .Values.ENVIRONMENT }}