apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.APP_DEVELOPMENT_NAME }}
  labels:
    {{- include "helm-labels" . }}
    {{- include "default-k8-labels" . }}
spec:
  capacity:
    storage: {{ .Values.PERSISTENT_VOLUME_SIZE }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: {{ .Values.NODE_DB_VOLUME_PATH }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - {{ .Values.NODE_HOSTNAME }}