apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.APP_DEVELOPMENT_NAME }}
  labels:
    {{- include "helm-labels" . }}
    {{- include "default-k8-labels" . }}
spec:
  type: NodePort
  ports:
  - name: {{ .Values.APP_DEVELOPMENT_NAME }}
    protocol: TCP
    port: {{ .Values.DASHBOARD_CONTAINER_PORT }}
    targetPort: {{ .Values.DASHBOARD_POD_PORT }}
    nodePort: {{ .Values.DASHBOARD_NODE_PORT }}
  selector:
    app.kubernetes.io/name: {{ .Values.APP_DEVELOPMENT_NAME }}
  